-- Base Camp seed data. Run AFTER base-camp-supabase.sql.
-- Loads your 8 clients, 15 prospects and 5 parked items.

insert into bc_clients (id, data) values ('buxton-inn', '{"id": "buxton-inn", "lead": "", "name": "Buxton Inn", "nextAction": "", "pulse": "Going back and forth on the Distinctive Supply order. Invoice went out Sep 16, payment landed, most of it ships today. Now we''re stuck on backordered brackets and whether to pay $126 to air the rest.", "recap": "", "recapBullets": ["No meetings on the calendar in this window. All of it ran over email.", "Julie sent the purchase request to Dora at Distinctive Supply Sep 15, the account was set up Sep 16, payment landed and most of the order ships Sep 18.", "DECISION PENDING: brackets are the holdup. Only one case of double brackets is in stock, the rest are backordered, and UPS Next Day Air is quoted at $126.66 on top.", "The Apotheke order had a voided shipping label Sep 17, reissued the same day, new tracking 1Z1372KR0334852112.", "You invoiced the Buxton Inn Sep 16, attention Kevin Showe, copy Blake Kuhn, set up for credit card with the surcharge passed through."], "recapPeriod": "Sep 4 to Sep 18", "recapUpdatedAt": "2026-09-18T14:20:00.000Z", "status": "active", "tickedOn": null}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_clients (id, data) values ('choobies', '{"id": "choobies", "lead": "Carolyn", "name": "Choobies", "nextAction": "Air into Louisville vs final-mile delivery, and the CPC pending the Intertek retest.", "pulse": "New hourly scope signed and DocuSigned. Zach is now pushing back on the cost of the pre-shipment inspection, and that needs an answer before Monday or the Sep 21 slot is gone.", "recap": "", "recapBullets": ["Met: Choobies weekly TB Sep 10, Choobies TB Sep 11, working session Sep 17.", "Scope 3.1 closed. Zach turned down the retainer so Julie rebuilt it hourly at $350 scheduled and $400 unscheduled, combined and not doubled when you are both on. He questioned the rate, Julie answered it flat, he said ready to execute Sep 14, DocuSign went Sep 15.", "Freight landed on you. Julie handed over the ECU quotes Sep 14 with the note that the nine quotes were not comparable and all expired that day.", "Thirteen boxes arrived at Zach''s Sep 15 and he is filling the inventory room.", "DUE IN DAYS: Julie is trying to book an in-line pre-shipment inspection at Advan for Sep 21 or 22 through Intertek (handed from Hotter Wei to Beryl Zhou). Zach pushed back Sep 18 wanting cost and options first, and pointedly noted he skipped it originally on our advice.", "Zach submitted the Safer Products registration Sep 17. The account is not live until CPSC reviews it."], "recapPeriod": "Sep 4 to Sep 18", "recapUpdatedAt": "2026-09-18T14:20:00.000Z", "status": "active", "tickedOn": null}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_clients (id, data) values ('cricket', '{"id": "cricket", "lead": "", "name": "Cricket", "nextAction": "Wind-down: agree what the finite hourly support actually covers, in writing.", "pulse": "Marked winding down, running at full speed. Six open threads, Julie waiting on Cricket for box sizes and keychain specs, and the factories shut Sep 25 for Mid-Autumn.", "recap": "", "recapBullets": ["Met: cricket Sep 15.", "Marked winding down, running at full engagement volume. This is the busiest thread in the inbox.", "Julie ran the GMA financials Sep 18 at 2,000 units per kit: It''s Sugar at the 7% invoice structure against the ABC revenue share plus RappAround''s 10% commission.", "Keychains: four options priced at 2,000 units. Julie told Nancy Sep 18 to hold everything because Cricket has still not chosen material or size.", "Blocked on the client: final box sizes for the Original 4 kits went out Sep 16, Julie chased Sep 18, and she cannot go to Volkan until Cricket and Katie answer.", "Also open: fingerpaint kit reformulation, cups and stirrers (Elva cannot quote without stated goals), and the Reno delivery on AWB 501-20328792 which you confirmed received Sep 4.", "DUE: suppliers close for Mid-Autumn Festival Sep 25 to 27 and again Oct 1 to 8. Anything needing a factory answer has to land before Sep 25."], "recapPeriod": "Sep 4 to Sep 18", "recapUpdatedAt": "2026-09-18T14:20:00.000Z", "status": "winding", "tickedOn": null}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_clients (id, data) values ('drr-museum-store', '{"id": "drr-museum-store", "lead": "Carolyn", "name": "DRR Museum Store (State Dept)", "nextAction": "Vendor delivery window Oct 1-5, store opens end of October. Audit the Ariba Vendor Master against the OK to Buy list.", "pulse": "Sally is paying down Priority 1 and has asked us twice for the rest of the invoices. Faire flagged the account Wednesday. Delivery window opens Oct 1 and the print shop payment has a two-day squeeze.", "recap": "", "recapBullets": ["Met: Transact Faire Wholesale Orders Sep 8, DRR purchasing call with Sally and Virginia Sep 14.", "Cash is the constraint. You sent Priorities and Path Forward Sep 15 and Virginia Hart answered the same day: roughly $17K on the purchasing card, another $50K being opened, $150K targeted between Sep 15 and Sep 28, and explicitly no longer rushing.", "Sally has been clearing Priority 1 through the week: Rowe Pottery, WS Game Company SO42291, Philadelphia Print Shop WN1999, Christopher Spitzmiller.", "OPEN ON US: Sally has now asked twice for the remaining Priority 1 invoices, Rifle Paper Co. at $2,100 named specifically. That is the ball sitting in our court.", "RISK: Faire flagged a problem with the account Sep 17 and Julie is still pulling detail out of support. Eight DRR vendors run through Faire.", "DUE: Philadelphia Print Shop needs payment by Sep 30 to ship Oct 2, and the card funds do not close until Sep 28. Vendor delivery window is Oct 1 to Oct 5 and the store opens end of October.", "Julie opened four new pen vendors Sep 18: Karas, Edison, Fisher Space Pen, Tactile Turn."], "recapPeriod": "Sep 4 to Sep 18", "recapUpdatedAt": "2026-09-18T14:20:00.000Z", "status": "active", "tickedOn": null}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_clients (id, data) values ('idear', '{"id": "idear", "lead": "", "name": "IDEAR / Paul Fino", "nextAction": "", "pulse": "Chrissy wants a standing check-in and we sent times Sep 16 that haven''t come back yet. Paul''s first fragrance samples are out with the full brand team.", "recap": "", "recapBullets": ["Met: IDEAR + P+P costing TB Sep 10, IDEAR quick connect Sep 16, internal Paul Fino session on financial plans and unit costs Sep 8.", "Chrissy asked for the quick connect the same morning she wanted it. Agenda was project pathing next steps and setting an ongoing check-in cadence.", "COMING UP: you proposed biweekly standup times Sep 16 for Sep 22 and Sep 23. Not confirmed back yet.", "Chrissy sent the Sniff Sesh questionnaire Sep 16 to the full brand team (IPG, Custom Essence, Townhouse, Nightingale) as Paul''s first round of fragrance samples went out."], "recapPeriod": "Sep 4 to Sep 18", "recapUpdatedAt": "2026-09-18T14:20:00.000Z", "status": "active", "tickedOn": null}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_clients (id, data) values ('sabal-swim', '{"id": "sabal-swim", "lead": "Carolyn", "name": "Sabal Swim", "nextAction": "Preston asked whether we do pricing strategy. Scope it before the interest cools.", "pulse": "A few emails back and forth on the buy. Preston''s CFO is questioning the 150 percent growth assumption, we answered Tuesday, and it''s been quiet since. Pricing work is sitting right there unscoped.", "recap": "", "recapBullets": ["Met: Reorder review Sep 4, with Preston sharing the Otter notes after.", "Preston caught that the summary totals were not recalculating Sep 9. You fixed and explained it the same day.", "Large in the Hampton went back into the order after Hartley pushed, on the evidence that it was the only size in the line that sold out.", "WATCH: Sep 15 Preston said he and his CFO are questioning whether planning to 150% growth is right given cash flow. You answered Sep 16 that the forecast comes from their own sales history and the growth target set together, with no consumer spending overlay. No reply since.", "Preston left a review Sep 14 and said in writing that pricing is the next engagement.", "COMING UP: the pricing scope. Granola has us owing a menu of project services with pricing, covering retail pricing strategy, cost and margin analysis, and below-the-line opportunities. Not sent."], "recapPeriod": "Sep 4 to Sep 18", "recapUpdatedAt": "2026-09-18T14:20:00.000Z", "status": "active", "tickedOn": null}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_clients (id, data) values ('splat-lab', '{"id": "splat-lab", "lead": "Julie + Adrian", "name": "Splat Lab", "nextAction": "Decide whether the post-Milestone-2 import coaching gets scoped and billed, or gets a stop date.", "pulse": "eFiling finally done Sep 14 so freight can move. Still doing unpaid import coaching five weeks after the engagement closed at Milestone 2.", "recap": "", "recapBullets": ["No meetings on the calendar in this window. All of it ran over email with Taylor Vecchio.", "UNBLOCKED: the CPSC eFiling account was the thing holding up freight. Adrian sent the setup steps Sep 3 and chased Sep 5. Taylor got it done a different way and confirmed Sep 14. Freight can now be organized.", "Julie told Taylor Sep 16 to skip the customs bond form: it is optional, and for a single shipment the no-paperwork bond option is the right one.", "Taylor is learning importing in real time and asked broader questions, since she is bringing in supplies for her other programs too. Julie walked her through DDP versus FOB and where the cost actually sits.", "FLAG: Adrian noted many Splat Lab kit components classify as chemicals, so a US-based freight forwarder is the call for this first shipment. That constrains who can handle it.", "Worth naming at the touch base: this engagement formally wrapped at Milestone 2 on Aug 25 and has been running on unpaid goodwill ever since. It is a tripwire case."], "recapPeriod": "Sep 4 to Sep 18", "recapUpdatedAt": "2026-09-18T15:30:00.000Z", "status": "active", "tickedOn": null}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_clients (id, data) values ('wellow', '{"id": "wellow", "lead": "Julie + Carolyn", "name": "Wellow", "nextAction": "Thai Sock / PackYak: confirm the three Heart Healthy releases land as planned.", "pulse": "Contract extension signed, except Julie thinks we signed the wrong version and nobody has sorted that out. Three Thai Sock lots moving, Lot 1 lands Sep 23, and both Dongjing POs go sea on the 25th.", "recap": "", "recapBullets": ["Met: Monday Morning Meeting Sep 8, Plan Pivot/Sean Sep 9 and Sep 15, Pablo weekly Sep 11, Product Business Review Sep 7 and Sep 14, Purchasing Touchbase and Summer 2027 Direction both Sep 14.", "Contract extension signed. Sean sent the agreement Sep 10, you signed and returned Sep 15. Julie thinks it is the wrong version (the one with the AI restriction language); she had already signed an updated one from Megan. Still unresolved.", "Thai Sock: Lot 1 loaded Sep 14 with draft AWB. Lots 2 and 3 confirmed Sep 16, Lot 2 at 9,480 pairs in 92 cartons and Lot 3 at 12,000 pairs in 115 cartons.", "DUE: Lot 1 lands Sep 23. You sent the signed power of attorney and EIN Sep 17 so TRK can file the entry in time. Lot 2 loads Sep 22. Lot 3 flight schedule still not issued.", "Dongjing: Sean asked to move from air to sea, you priced four options, and POs R12.1 and 29.1 now ship fast sea together Sep 25.", "Julie sent the open-order reconciliation (Untangling Wellow Receipts) Sep 17 and you are loading it into the dashboard. She built it by hand, so it is worth deciding whether that becomes automated."], "recapPeriod": "Sep 4 to Sep 18", "recapUpdatedAt": "2026-09-18T14:20:00.000Z", "status": "active", "tickedOn": null}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_prospects (id, data) values ('n-hud', '{"category": "unclosed", "detail": "RFQ 86615426Q00017 submitted Jul 23. Would have required hiring to deliver.", "id": "n-hud", "lastTouch": "2026-07-23", "name": "HUD contracting", "nextStep": "Check the award status, and decide whether federal marketing RFQs are a lane we want", "org": "U.S. Dept of Housing and Urban Development", "owner": null, "status": null, "value": null}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_prospects (id, data) values ('n-lovestruck', '{"category": "unclosed", "detail": "Merchandising concept direction deck sent Aug 11 after a Granola-noted discovery call. They reviewed proposals through Aug 18, then passed Aug 24: decided to go in a different direction. You and Julie replied warmly and left the door open.", "id": "n-lovestruck", "lastTouch": "2026-08-24", "name": "Rachel / Marley Chase", "nextStep": "Lost on merit, not on silence. Worth a check-in in Q1 to see how the other direction went", "org": "Lovestruck Books", "owner": null, "status": null, "value": null}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_prospects (id, data) values ('n-megan-trudie', '{"category": "unclosed", "detail": "Met Aug 13, proposal sent the same day, followed up Aug 18. She replied Sep 3: apologized for going quiet, hit her first $10K month in August, asked to circle back in December. Sometimes remembered as Posie.", "id": "n-megan-trudie", "lastTouch": "2026-09-04", "name": "Megan", "nextStep": "She named December herself. Reminder parked for Nov 30", "org": "Trudie (quilted homewares)", "owner": null, "status": null, "value": null}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_prospects (id, data) values ('n-morgan-kirchner', '{"category": "unclosed", "detail": "Mahjong sourcing proposal out since Jul 23. Follow-ups Jul 28, Aug 4 and Aug 18, including two warm non-sales notes. No answer to any of them.", "id": "n-morgan-kirchner", "lastTouch": "2026-08-18", "name": "Morgan Kirchner", "nextStep": "One more warm note with a real reason, then let it go", "org": "Three Daughters Co.", "owner": null, "status": null, "value": null}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_prospects (id, data) values ('p-clearwater', '{"category": "scope", "detail": "Three-phase merchandising engagement: intro packet and starting scope", "id": "p-clearwater", "lastTouch": "2026-09-17", "name": "Ella Rouelle", "nextStep": "Follow up if it is quiet by Sep 26", "org": "Clearwater Mercantile", "owner": null, "status": "out", "value": "$45K / $90K / $20K+ mo"}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_prospects (id, data) values ('p-hud', '{"category": "scope", "detail": "RFQ 86615426Q00017, Marketing Support Services for HUD Housing Surveys", "id": "p-hud", "lastTouch": "2026-07-23", "name": "Diaz / Gist", "nextStep": "No award notice in eight weeks. Check status, and decide if we would even staff it", "org": "HUD", "owner": null, "status": "out", "value": "quoted"}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_prospects (id, data) values ('p-sabal-pricing', '{"category": "scope", "detail": "Pricing strategy, plus a menu of project services", "id": "p-sabal-pricing", "lastTouch": "2026-09-16", "name": "Preston Lynn", "nextStep": "Send the services menu: retail pricing, cost and margin, below the line", "org": "Sabal Swim", "owner": null, "status": "drafting", "value": "TBD"}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_prospects (id, data) values ('p-three-daughters', '{"category": "scope", "detail": "Mahjong sourcing, 4 to 6 weeks, three vetted finalists", "id": "p-three-daughters", "lastTouch": "2026-08-18", "name": "Morgan Kirchner", "nextStep": "Three follow-ups out with no reply. Decide: one more, or move to never closed", "org": "Three Daughters Co.", "owner": null, "status": "out", "value": "not disclosed"}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_prospects (id, data) values ('w-andrew-shibata', '{"category": "warm", "detail": "Stayed in touch all year unprompted, offers referrals and intros, asked if you would be at High Point. Said the assortment work is a 2027 or 2028 push.", "id": "w-andrew-shibata", "lastTouch": "2026-08-21", "name": "Andrew Shibata", "nextStep": "High Point, and pin down whether the 2027 push has a real date", "org": "Jeffan (came through Jola USA)", "owner": null, "status": null, "value": null}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_prospects (id, data) values ('w-chrissy-montera', '{"category": "warm", "detail": "Brought P&P into Paul Fino / IDEAR. She is a referral source, not only a collaborator.", "id": "w-chrissy-montera", "lastTouch": "2026-09-16", "name": "Chrissy Montera", "nextStep": "Already active on IDEAR. Ask what else is in her book", "org": "Miss C-Suite", "owner": null, "status": null, "value": null}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_prospects (id, data) values ('w-elisa-70deg', '{"category": "warm", "detail": "Engagement closed Jul 30 with a final close and dashboard walkthrough. Runs the store setup side herself, so she knows what the tool is worth.", "id": "w-elisa-70deg", "lastTouch": "2026-07-30", "name": "Alisa Durando", "nextStep": "Seven weeks quiet. Check in on how the dashboard is actually being used", "org": "70 Degrees Life", "owner": null, "status": null, "value": null}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_prospects (id, data) values ('w-lauren-ganim', '{"category": "warm", "detail": "Pro Shop inventory and sales reset closed Apr 2026. Said she would come back with details on the new location. New HQ has a Trader Joe''s next door and a PT patient base walking through daily.", "id": "w-lauren-ganim", "lastTouch": "2026-06-04", "name": "Lauren Ganim", "nextStep": "Ask how the new HQ build landed. Three months quiet.", "org": "Chalkd Apparel", "owner": null, "status": null, "value": null}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_prospects (id, data) values ('w-lauren-mazzei', '{"category": "warm", "detail": "Came to P&P for help on her deck in June, took the input, was invoiced. Small engagement but she sought you out.", "id": "w-lauren-mazzei", "lastTouch": "2026-06-03", "name": "Lauren Mazzei", "nextStep": "Julie asked how the terms shook out and never got an answer. Ask again as a human", "org": "Past Midnight", "owner": null, "status": null, "value": null}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_prospects (id, data) values ('w-preston-hartley', '{"category": "warm", "detail": "2027 restock buy delivered. Left a public review Sep 14 and said in writing that pricing is next.", "id": "w-preston-hartley", "lastTouch": "2026-09-16", "name": "Preston Lynn & Hartley", "nextStep": "Warm and active. Convert the pricing interest before the CFO conversation cools it", "org": "Sabal Swim", "owner": null, "status": null, "value": null}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_prospects (id, data) values ('w-shelia-butler', '{"category": "warm", "detail": "The agency that took a chance on P&P in January and brought the Jeffan work. Wrapped April. Julie introduced her to Chrissy Montera in June.", "id": "w-shelia-butler", "lastTouch": "2026-06-18", "name": "Shelia Butler", "nextStep": "Nothing since the last invoice in June. Overdue for a real check-in, not an invoice", "org": "Jola USA", "owner": null, "status": null, "value": null}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_agenda (id, data) values ('seed-holiday-replen', '{"addedAt": "2026-09-18T12:00:00.000Z", "addedBy": null, "doneAt": null, "id": "seed-holiday-replen", "section": "clients", "status": "open", "surfaceOn": "2026-10-26", "text": "Before the holidays: DRR replen plan for the November and December event weeks."}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_agenda (id, data) values ('seed-smithsonian', '{"addedAt": "2026-09-18T12:00:00.000Z", "addedBy": null, "doneAt": null, "id": "seed-smithsonian", "section": "scopes", "status": "open", "surfaceOn": null, "text": "Smithsonian Enterprises: next move on Ray Moore, SVP Retail. Museum store as a named category, not a one-off."}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_agenda (id, data) values ('seed-tripwires', '{"addedAt": "2026-09-18T12:00:00.000Z", "addedBy": null, "doneAt": null, "id": "seed-tripwires", "section": "catchall", "status": "open", "surfaceOn": null, "text": "Walk through the client tripwire list and pick ONE to run for a month. Vote: the change-order line."}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_agenda (id, data) values ('seed-trudie-december', '{"addedAt": "2026-09-18T15:00:00.000Z", "addedBy": null, "doneAt": null, "id": "seed-trudie-december", "section": "scopes", "status": "open", "surfaceOn": "2026-11-30", "text": "Circle back to Megan at Trudie. She asked for December, after her busiest season."}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_agenda (id, data) values ('seed-wellow-trueup', '{"addedAt": "2026-09-18T12:00:00.000Z", "addedBy": null, "doneAt": null, "id": "seed-wellow-trueup", "section": "clients", "status": "open", "surfaceOn": "2026-10-12", "text": "Wellow hours true-up now that the contract tripled. Are we actually billing what we''re working?"}'::jsonb)
  on conflict (id) do update set data = excluded.data;
insert into bc_meta (id, data) values ('refresh', '{"status":"idle","completedAt":null}'::jsonb)
  on conflict (id) do update set data = excluded.data;
